import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./HeaderButton"
import HeaderButton from "./HeaderButton";
import HeaderDropdownMenu from "./HeaderDropdownMenu";
import { ToastProvider } from "../components/ToastContext";
import { Card } from '../components/ui/Card'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SSIS-Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log(`Someone logged in at ${new Date()}`)
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <Card className="my-header">
            <HeaderButton myLink={"/table/colleges"}> College </HeaderButton>
            <HeaderButton myLink={"/table/programs"}> Programs </HeaderButton>
            <HeaderButton myLink={"/table/students"}> Students </HeaderButton>
          </Card>
        </header>
        <main className="my-main">
          <ToastProvider>
            {children}
          </ToastProvider>
        </main>
      </body>
    </html>
  );
}
